name: tinterview
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12
  - numpy
  - pandas
  - fastapi
  - pip
  - setuptools>=65
  - wheel
  - websockets
  - sounddevice
  - webrtcvad
  - pydub
  - requests
  - ffmpeg  # Required for handling audio conversions
  - portaudio  # Required for sounddevice (may need manual installation on some systems)
  - pip:
      - langchain-openai
      - uvicorn  # For running FastAPI server


